name: Test Project
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Download the code
      - name: Get node
        uses: actions/checkout@v3
      # Install NodeJS version
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      # Install dependencies
      - name: Install dependencies
        run: npm ci
      # Run tests
      - name: Run tests
        run: npm test
